[project]
name = "ur3-cli"
version = "0.1.0"
description = "UR3 MoveIt 2 CLI for ROS 2 Jazzy"
requires-python = "==3.12.3"
dependencies = [
    "lark>=1.2.2",
    "numpy>=2.3.2",
    "packaging>=25.0",
    "pyyaml>=6.0.2",
]
